### ISSUE TITLE
LabProtocol confusion

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#331] opened 2019-06-20 09:49 UTC
I have a major problem with the proposal. It is not clear if it is for a definition or for a history.

Description: "This LabProtocol profile specification presents the markup for describing a LabProtocol". This is a tautology. The description should say what the LabProtocol profile is for. Is it a definition for someone *to* follow, or a record of what *was done*? They are not the same thing.

ChEBI:reagent and instrument could be definitions of what to use. However, the description of Instrument states that it is "The object that helped the agent perform the action". Note it says "the object" not the type/class of object, which suggests it is an actual physical instrument. So, to follow the example, not "a pen" but "this blue Bic pen that I bought last week and is on my desk".

Similarly with sample, the description suggests that it is an actual sample, e.g. a "record in a Dataset".

duration though reads as if it is a definition - "the time it takes" not "the time it took".

hasPart definitely reads as if it is a definition.

software also is for a definition.

step, though, is described for a record. "the step by step process followed in this protocol" NOT "the step by step process to be followed when using this protocol".

**Comment by alaninmcr** [comment] 2019-06-20 09:49
Alasdair Grey suggested that "it make sense to suggest an approach similar to courses where there is a generic Course description and then specific instances of the course are described as CourseInstance."

**Comment by AlasdairGray** [comment] 2019-06-28 16:30
@alaninmcr do you know which version you looked at. At the time you did this, there was only an old version available on the Bioschemas website. There was a newer version of the type available on appspot. We have now transferred the newer version to the Bioschemas website:
- Type: https://bioschemas.org/types/drafts/LabProtocol/
- Profile: https://bioschemas.org/specifications/drafts/LabProtocol/

Are your issues still relevant with the revised version?

**Comment by alaninmcr** [comment] 2019-07-02 09:50
Looking at the revised version, the same issues still apply.

**Comment by ljgarcia** [comment] 2019-09-06 01:43
@alaninmcr The idea here is to model labprotocols as they are published. For instance, those at https://bio-protocol.org/ We will work this month on the standting issues via pull requests.

**Comment by oxgiraldo** [comment] 2020-07-29 14:44
**@alaninmcr** I don't understand your comment. Please if you feel it should be rewritten, go ahead and rewrite so that I can evaluate it and thus understand it better. Once I get the definition as you feel it should be, then I will be able to assess it and have a definitive definition. otherwise it will take longer because I just don't understand what the issue is. For all the rest please take a look at the new version 0.4 (a pull request was done by Leyla last week: https://github.com/BioSchemas/bioschemas.github.io/pull/307), and let me know.

**Comment by ljgarcia** [comment] 2020-08-03 13:40
Hi @alaninmcr a new version is available already. 

Could you please have a look and see how the LabProtocol type/profile can be improved? The latest version is available at https://bioschemas.org/profiles/LabProtocol/0.4-DRAFT-2020_07_23/

You mentioned "It is not clear if it is for a definition or for a history". What do you refer to with "history"? I am wondering if this is a problem of "class" vs "individual" vs "data-record". We had an issue with the protein spec, same as UniProt proteins, it does not reflect an actual protein but somehow a class of proteins which have been given an accession. This could be the issue with some of the properties you mentioned, for instance "Similarly with sample, the description suggests that it is an actual sample, e.g. a "record in a Dataset". In Bioschemas the line between data record (UniProt entry as described in a web page) and the actual thing (UniProt entry) is kind of blur. In fact, the DataRecord type has not been fully defined yet (some people think it is needed some others find it unnecessary). If you comments go in a different direction, please provide some more information.

The main idea behind LabProtocol is published LabProtocols, that is why it is a subclass of CreativeWork. Not sure what the analogy with Course and CourseInstance addresses. Would be the idea to have a generic LabProtocol and then a concrete instance? One of the differences between Course and CourseInstance is that the latter happens at a particular time in a particular place and is taught by a particular person. I am not sure I see how this would apply to LabProtocol. An example would be great.

Thanks

**Comment by ljgarcia** [comment] 2020-08-03 13:45
@oxgiraldo While we get more information from @alaninmcr there are some of his comments we could address already:

* Quote ---"Description: "This LabProtocol profile specification presents the markup for describing a LabProtocol". This is a tautology. The description should say what the LabProtocol profile is for. Is it a definition for someone to follow, or a record of what was done? They are not the same thing." End of quote--- The definition should include some information regarding the sort of LabProtocols that are targeted here, it could be a link to one of the journals publishing the sort of lab protocols you refer to or to an actual protocol or both, this should help to clarify what is meant by "Lab Protocol" here. I guess it can be both a definition for someone to follow or a record of what was done depending on the information provided in the actual Lab Protocol, please have a look. Thanks

**Comment by alaninmcr** [comment] 2020-08-06 09:27
Hello

I checked the latest version; the change in descriptions addresses the issues I had. I think it is now OK.

--
Alan

The University of Manchester belongs to the European R&D infrastructure IBISBA 1.0
The project has received funding from the European Union’s Horizon 2020
Research and Innovation Programme under grant agreement No 730976.
To find out more visit https://www.ibisba.eu

________________________________________

**Comment by gtsueng** [comment] 2022-12-19 22:48
This appears to have been addressed by https://github.com/BioSchemas/bioschemas.github.io/pull/320. Unless @oxgiraldo suggests otherwise, it will be closed.

**Comment by ljgarcia** [comment] 2022-12-23 12:05
@gtsueng I think we can close this one. Thanks

**Closed as completed** 2023-01-05 18:22 UTC
Labels: type: LabProtocol, pending closure
